[tool.poetry]
name = "remi"
version = "0.1.0"
description = "A personal Discord bot for my Discord server"
authors = ["PythonTryHard <31789326+PythonTryHard@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10, <3.11"
hikari = {extras = ["speedups"], version = "^2.0.0-alpha.104"}
hikari-lightbulb = "^2.1.0"
uvloop = "^0.16.0"
python-dotenv = "^0.19.2"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]
pre-commit = "^2.16.0"
black = "^21.12b0"
pudb = "^2021.2.2"
pylint = "^2.12.2"
python-dotenv = "^0.19.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

